language: python
python:
    - 2.7
    - 3.4
    - 3.5
script:
    - pip install coveralls coverage
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
    - pip install .
    - coverage run --source=httsleep py.test
after_success:
    - coveralls
os:
    - linux
